### ISSUE TITLE
Copy/Layout Changes

### ISSUE THREAD

**Issue by zachmccormick** [HoneyCoHomes/Website#24]
[https://www.dropbox.com/s/hqxdljti1x4wey2/Screenshot%202016-11-10%2009.19.43.png?dl=0](https://www.dropbox.com/s/hqxdljti1x4wey2/Screenshot%202016-11-10%2009.19.43.png?dl=0)

[https://www.dropbox.com/s/w9swryiaedk13km/Screenshot%202016-11-10%2009.20.48.png?dl=0](https://www.dropbox.com/s/w9swryiaedk13km/Screenshot%202016-11-10%2009.20.48.png?dl=0)

(remove the statistic paragraph that is unfinished here)

[https://www.dropbox.com/s/g22qiu411odgia9/Screenshot%202016-11-10%2009.21.08.png?dl=0](https://www.dropbox.com/s/g22qiu411odgia9/Screenshot%202016-11-10%2009.21.08.png?dl=0)

[https://www.dropbox.com/s/wgowa9fdehymqpu/Screenshot%202016-11-10%2009.27.07.png?dl=0](https://www.dropbox.com/s/wgowa9fdehymqpu/Screenshot%202016-11-10%2009.27.07.png?dl=0)

Add instagram icon + link to footer

**Comment by zachmccormick** [comment]
```*Landing section (home)* 
1. "welcome to your unRetirement", please remove "to your" so that it reads 
"Welcome to unRetirement" 
2. My "learn more" button is very close to the bottom of the screen, do we 
want that? 
3. "Learn more" button is not functional

*About section:* 
1. Text needs an overhaul. 
2. Where is the information dot going to take someone? To another page 
within Honeyco.com? or outside? 
3. Quick update to final sentence, "Make the most of unRetirement in a 
HoneyCo home" -- we generally want to remove "your" "you", etc... 
4. There's no link to a video here. Do we want one? I do. But does our lead 
designer/whole design team agree? 
5. I can scroll down slightly on this page. Because of that I see the nav 
bar is transparent. It shouldn't be.

*Products:* 
1. Button shows up at bottom of screen, even though there's a ton of grey 
space available above the text. 
2. Oddly, I can scroll down on this page, unlike the others. Because of 
that I see the nav bar is transparent. It shouldn't be. 
3. Clicking on the pair of folks looking at the computer takes me to the 
"About" section 
4. Overhaul language. 
5. I can scroll down a lot on this page to reveal blank honeyco bluegreen.

*Society* 
1. Overhaul language to include less us vs you, 
2. Should be able to exit video window with an esc key or click on the main 
page. 
3. Page scrolls slightly

Homes and care packages haven't been reviewed, looks like there aren't any 
additional changes from my conversation yesterday.```

**Comment by MeganCFord** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Website: copy/layout changes](https://trello.com/c/PE0yL2K9/88-website-copy-layout-changes)
