### ISSUE TITLE
Change Header/Navbar

### ISSUE THREAD

**Issue by zachmccormick** [HoneyCoHomes/Website#25]
[https://www.dropbox.com/s/hqxdljti1x4wey2/Screenshot%202016-11-10%2009.19.43.png?dl=0](https://www.dropbox.com/s/hqxdljti1x4wey2/Screenshot%202016-11-10%2009.19.43.png?dl=0)

Do not include "Log In", but do include the one-page scrolling links on the left and the links to separate pages on the right

**Comment by MeganCFord** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Website: change header/navbar](https://trello.com/c/5PzoApdh/87-website-change-header-navbar)
